#include <curses.h>
#include <stdio.h>
#include <sys/time.h>
#include <signal.h>
#include <stdlib.h>

void drawGround();
void tuxioRun();
void alrmHandle();

void setup()
{
	curs_set(0);	
	int tick = set_ticker(20);//SIGALM set every 20ms	
	int status = system("xset r rate 100 10");
	signal(SIGALRM, alrmHandle);
	initscr();	 //initialize the screen
	crmode();
	noecho();
	clear();
	drawGround();	//draw the ground
	refresh();
	nodelay(stdscr, TRUE);
	cbreak();
}

void drawGround()
{
	int i;	//index variable
	for(i = 0; i < COLS; i++)
	{
		move(LINES-2, i);	//move to 2 above the bottom of the screen, index
		addch('_');		//draw an underscore there
	}
}

void alrmHandle()
{}	//empty method to catch SIGALRM signal generated by ticker

